# Generated by Django 5.2.11 on 2026-03-02 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('offer_utl', models.URLField(blank=True)),
                ('applied_date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('applied', 'Wysłano'), ('interview', 'Interview'), ('rejected', 'Rejected'), ('offer', 'Offer')], default='applied', max_length=100)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
    ]
